package com.lucky.cat.updown.sql;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lucky.cat.updown.sql.DownloadModel;

import com.lucky.cat.updown.sql.DownloadModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadModelDaoConfig;

    private final DownloadModelDao downloadModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadModelDaoConfig = daoConfigMap.get(DownloadModelDao.class).clone();
        downloadModelDaoConfig.initIdentityScope(type);

        downloadModelDao = new DownloadModelDao(downloadModelDaoConfig, this);

        registerDao(DownloadModel.class, downloadModelDao);
    }
    
    public void clear() {
        downloadModelDaoConfig.getIdentityScope().clear();
    }

    public DownloadModelDao getDownloadModelDao() {
        return downloadModelDao;
    }

}
