package com.lucky.cat.updown.sql;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lucky.cat.updown.sql.DownloadModel;
import com.lucky.cat.updown.sql.DownloadHistoryModel;

import com.lucky.cat.updown.sql.DownloadModelDao;
import com.lucky.cat.updown.sql.DownloadHistoryModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadModelDaoConfig;
    private final DaoConfig downloadHistoryModelDaoConfig;

    private final DownloadModelDao downloadModelDao;
    private final DownloadHistoryModelDao downloadHistoryModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadModelDaoConfig = daoConfigMap.get(DownloadModelDao.class).clone();
        downloadModelDaoConfig.initIdentityScope(type);

        downloadHistoryModelDaoConfig = daoConfigMap.get(DownloadHistoryModelDao.class).clone();
        downloadHistoryModelDaoConfig.initIdentityScope(type);

        downloadModelDao = new DownloadModelDao(downloadModelDaoConfig, this);
        downloadHistoryModelDao = new DownloadHistoryModelDao(downloadHistoryModelDaoConfig, this);

        registerDao(DownloadModel.class, downloadModelDao);
        registerDao(DownloadHistoryModel.class, downloadHistoryModelDao);
    }
    
    public void clear() {
        downloadModelDaoConfig.getIdentityScope().clear();
        downloadHistoryModelDaoConfig.getIdentityScope().clear();
    }

    public DownloadModelDao getDownloadModelDao() {
        return downloadModelDao;
    }

    public DownloadHistoryModelDao getDownloadHistoryModelDao() {
        return downloadHistoryModelDao;
    }

}
