package com.lucky.cat.updown.sql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOAD_HISTORY_MODEL".
 */
public class DownloadHistoryModel {

    private Long id;
    private String downLoadUrl;
    private String savePath;
    private String fileName;
    private Long fileSize;
    private java.util.Date createTime;

    public DownloadHistoryModel() {
    }

    public DownloadHistoryModel(Long id) {
        this.id = id;
    }

    public DownloadHistoryModel(Long id, String downLoadUrl, String savePath, String fileName, Long fileSize, java.util.Date createTime) {
        this.id = id;
        this.downLoadUrl = downLoadUrl;
        this.savePath = savePath;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDownLoadUrl() {
        return downLoadUrl;
    }

    public void setDownLoadUrl(String downLoadUrl) {
        this.downLoadUrl = downLoadUrl;
    }

    public String getSavePath() {
        return savePath;
    }

    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

}
